inputdir:
        "aligned"
outputdir:
        "trees"
datatype:
        "aa"
subsmodel:
        "LG"
pinvariants:
        "0.0"
gammashape:
        "1.0"
ratecategs:
        "4"
bootstraps:
        "1"
rseed:
        "1"
